// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller.js"
application.register("form", FormController)

import TomSelectController from "./tom_select_controller.js"
application.register("tom-select", TomSelectController)
